### PR TITLE
fix(tests): fixing wrong derived data path

### PR DESCRIPTION
**Pull request by milos1290**

### CODE REVIEW

**Comment by benmarten** [comment]
test this please

**Comment by benmarten** [comment]
test this please

**Comment by benmarten** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Pull request closed without merging**
