### PR TITLE
HTML in-app to cover status bar

### PR DESCRIPTION
**Pull request by alexisoyama**

### CODE REVIEW

**Comment by alexisoyama** [comment]
Blocked by slather error on jenkins. The test is passed though.

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
this this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
test this please

**Comment by milos1290** [comment]
Rebase from develop please.

**Comment by alexisoyama** [comment]
i already did.

**Comment by milos1290** [comment]
test this please

**Comment by alexisoyama** [comment]
@milos1290 can you review the code? We can figure out the Jenkins issue afterwards.

**Comment by milos1290** [comment]
test this please

**Pull request merged**
