### PR TITLE
fix sqlite crash

### PR DESCRIPTION
**Pull request by dejan2k**
What              | Where/Who
------------------|----------------------------------------
JIRA Issue        | [SDK-228](https://leanplum.atlassian.net/browse/SDK-228)
People Involved   | @dejan2k

### CODE REVIEW

**Review by nzagorchev — APPROVED** [review]

**Comment by ThePragmaticArt** [comment]
@dejan2k not sure if you were made aware (we've reached out to the support team regarding this), but it seems this particular PR may have started a chain of issues tied to implementing other SDK's using SQLite like Firebase. I can validate that this cause a slew of crashes in our production application (it's our top crash actually). Also see the following thread for some more references:
https://github.com/firebase/firebase-ios-sdk/issues/8024

**Comment by nzagorchev** [comment]
@ThePragmaticArt This is removed in PR #436 and released in 3.2.1

**Comment by ThePragmaticArt** [comment]
@nzagorchev thank you for the heads up. We receive a response from LP support noting the same thing and are preparing to deploy the updated SDK on our side.

**Comment by tschob** [comment]
I run into the same issue with 3.1.2 and the Firebase SDK (https://github.com/firebase/firebase-ios-sdk/issues/8437). Updating to 3.2.1 fixed the crashes. I'll also soon update my issue on Firebase to indicate that this change was the reason so that others are also aware.

**Comment by tschob** [comment]
One addition though: We spent multiple days with debugging the Firebase SDK instead of taking care of the source problem (this SDK). We could have saved quite some time if the existence of this crash and the availability of the fixed version **would have mentioned in the release notes**.

**Pull request merged**
