### PR TITLE
Lp 11236 fix push metrics

### PR DESCRIPTION
**Pull request by dejan2k**
What              | Where
------------------|----------------------------------------
JIRA Issue        | [LP-11236](https://leanplum.atlassian.net/browse/LP-11236)

### CODE REVIEW

**Comment by dejan2k** [comment]
> can you point me to where the track/log messages are, for Push Received and Push Opened ? I tried searching but failed strangely enough

I removed them, because I thought that we don't want them in the master branch. If you want I can put them back?

**Comment by e7mac** [comment]
> > can you point me to where the track/log messages are, for Push Received and Push Opened ? I tried searching but failed strangely enough
> 
> I removed them, because I thought that we don't want them in the master branch. If you want I can put them back?

Yes please! Once the metrics are working correctly, we want to be emitting track events so that we can use the metrics. I just wanted to avoid them in `master` until they were working correctly to maintain the purity of the data.

https://leanplum.atlassian.net/wiki/spaces/E2/pages/1016397848/Push+Notification+Delivery+Metrics

**Comment by memolopezmx** [comment]
escuseme may i start twice leanplum, because i made login with another  user in  my  app? but if i setUserId  i didn't receive push until y start again

**Comment by nzagorchev** [comment]
Hi @memolopezmx I believe the issue you are experiencing is related to a bug fixed with https://github.com/Leanplum/Leanplum-iOS-SDK/pull/370. If the problem continues, please email Leanplum support @ support@leanplum.com

**Comment by memolopezmx** [comment]
thank a lot!

**Pull request merged**
